---
title: "Assignment 1: Introduction"
author: "Meghan Seyler"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Lima_A01_Introduction.Rmd") prior to submission.

The completed exercise is due on <>.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer:My primary experience using R is from the introductory statistics course taught by Betsy Albright at the Nic School. I took that course in the Fall of 2020. I have basically no experience with Git other than the fact that I knew what it was and some of its basic functions.

2. Are there any components of the course about which you feel confident?

> Answer: I feel comfortable navigating R, knitting files, and google searching the things that I don’t know.

3. Are there any components of the course about which you feel apprehensive?

> Answer: The general set up with the cisco software/VPN, windows emulator, etc. was the most difficult part and I would have preferred to do that portion of the class in person (although I know that wasn’t an option this year).


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: [Link to Meghan's forked course repository](https://github.com/mbs71/Environmental_Data_Analytics_2022)



